### ISSUE TITLE
This error occur when code calls setState() from a timer or an animation callback.

### ISSUE THREAD

**Issue by filipp2911** [mhdmoh/redacted#5]
Hey there, thanks for library, but founded issue in the  code :
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
**code line: radacted_extensions.dart:372**

**Comment by filipp2911** [comment]
You can simply change line 371 :   Future.delayed(widget.configuration.animationDuration, () {  -->  WidgetsBinding.instance.addPostFrameCallback((_) {

**Comment by SardorbekR** [comment]
line 371:

```
class __RedactedFillWidgetState extends State<_RedactedFillWidget> {
  Timer? _timer;

  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _timer = Timer(widget.configuration.animationDuration, () {
        if (mounted) {
          setState(() {
            colored = !colored;
          });
        }
      });
    });
    super.initState();
  }


  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
...
```
